name: Refresh index

permissions: 
  contents: write

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ ! github.event.pull_request }}

      - uses: actions/checkout@v4
        if: github.event.pull_request
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
      
      - name: Setup packwiz
        run: |
          go install github.com/packwiz/packwiz@latest

      - name: Refresh index
        run: |
          packwiz refresh

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "pack.toml index.toml"
          default_author: github_actions
          message: "Update index"
          push: true
          fetch: false

